matrix:
  # include:
    - language: python
    python:
      - "3.7"
    dist: xenial
    services:
      - postgresql
    before_install:
      - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
      - sudo tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C /usr/bin
      - sudo chmod a+x /usr/bin/geckodriver
    install:
      - pip install pipenv
      - pipenv install
    env:
      - APP_SETTINGS="config.Development" DATABASE_URL="postgresql://localhost/magnetism"
    before_script:
      - nohup python3 src/app.py >/dev/null &
      - psql -c 'create database magnetism;' -U postgres
      - ./travis_db_setup.sh
    script:
      - pytest -r A
    after_script:
      - pkill python3

    # - language: node_js
    # node_js: "12.1.0"
    # before_script:
    #   - cd front_end
    # cache:
    #   directories:
    #     - node_modules
    # script:
    #     - npm test
