dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv install
env:
  - FLASK_ENV=development
before_script:
  - nohup python3 run.py >/dev/null &
script:
  - pytest
after_script:
  - pkill python3
